services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
    environment:
      - DB_FILE=/data/app.db
    volumes:
      - db_data:/data
    ports:
      - "8080:8080"

volumes:
  db_data: